locale: "en-US"
title: "Yo, I'm Shreeda"
title_separator: "-"
description: &description "Yo Pikabhu!!! Haha you will be caught checking out my website!! Just slide down once"
url: https://memetics19.github.io/
baseurl: "" # the subpath of your site, e.g. "/blog"
repository: "memetics19/memetics19.github.io"
future: true
read_more: "disabled" # if enabled, adds "Read more" links to excerpts

description: Shit Website
baseurl:
url:
github_username: memetics19

theme: jekyll-theme-leap-day

# Site Author
author:
  name: "Shreeda Bhat"
  avatar: "profile.png"
  email: shreeda.bhat@yahoo.com
  github: "memetics19"
  linkedin: "https://www.linkedin.com/in/anamitra-musib-69694a63/"

  
# Collections
  collections:
    Projects:
      output: true
      permalink: /:collection/:path/


# Build settings
markdown: kramdown
permalink: pretty


# https://github.com/academicpages/academicpages.github.io/blob/master/_config.yml
